#!usr/bin/perl -w
$PATH = "/project/fpga/vivado_prj";
$old_path1 = "\/old_path1\/";
$old_path2 = "\/old_path2\/";
$new_path = "\/new_path\/";
open(INPUT,"$PATH/input.txt") or die ("can not open file $!");
    open(OUTPUT,"> output.txt") or die ("can not close file $!");
         
         while(@array = <INPUT>){
###########################################################################
#    replace path of some elements
###########################################################################               
               foreach $n (@array){
                   $n =~ s/\-vhdl\ \-lib\ WORK//;
                   $n =~ s/add_file/add_files/;
                   $n =~ s/\-verilog//;
                   $n =~ s/old_path1/new_path/;
                   $n =~ s/old_path2/new_path/;
               }
###########################################################################
#    delete special lines in a array
###########################################################################

               my @array2 = splice @array,1296,500 ;
               print @array."\n";
###########################################################################
#  build a hash and put the element of array into it
###########################################################################

               my %list ={};
               my $i = 0;
               foreach $i (0 .. $#array){
                    $list{$array[$i]} = $i;               
               }
               
               my @array3 = sort keys %list;
               
               print OUTPUT "@array3";
         }
    
     close(OUTPUT);
  close(INPUT);
